/* valaccodestructmodule.c generated by valac, the Vala compiler
 * generated from valaccodestructmodule.vala, do not modify */

/* valaccodestructmodule.vala
 *
 * Copyright (C) 2006-2009  Jürg Billeter
 * Copyright (C) 2006-2008  Raffaele Sandrini
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 *	Raffaele Sandrini <raffaele@sandrini.ch>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valaccode.h>
#include <valagee.h>
#include <stdlib.h>
#include <string.h>


#define VALA_TYPE_CCODE_BASE_MODULE (vala_ccode_base_module_get_type ())
#define VALA_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModule))
#define VALA_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))
#define VALA_IS_CCODE_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_IS_CCODE_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_BASE_MODULE))
#define VALA_CCODE_BASE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_BASE_MODULE, ValaCCodeBaseModuleClass))

typedef struct _ValaCCodeBaseModule ValaCCodeBaseModule;
typedef struct _ValaCCodeBaseModuleClass ValaCCodeBaseModuleClass;
typedef struct _ValaCCodeBaseModulePrivate ValaCCodeBaseModulePrivate;

#define VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT (vala_ccode_base_module_emit_context_get_type ())
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContext))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_IS_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_CCODE_BASE_MODULE_EMIT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_CCODE_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaCCodeBaseModuleEmitContextClass))

typedef struct _ValaCCodeBaseModuleEmitContext ValaCCodeBaseModuleEmitContext;
typedef struct _ValaCCodeBaseModuleEmitContextClass ValaCCodeBaseModuleEmitContextClass;

#define VALA_TYPE_CCODE_STRUCT_MODULE (vala_ccode_struct_module_get_type ())
#define VALA_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModule))
#define VALA_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))
#define VALA_IS_CCODE_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_IS_CCODE_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_CCODE_STRUCT_MODULE))
#define VALA_CCODE_STRUCT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_CCODE_STRUCT_MODULE, ValaCCodeStructModuleClass))

typedef struct _ValaCCodeStructModule ValaCCodeStructModule;
typedef struct _ValaCCodeStructModuleClass ValaCCodeStructModuleClass;
typedef struct _ValaCCodeStructModulePrivate ValaCCodeStructModulePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))

#define VALA_TYPE_TYPEREGISTER_FUNCTION (vala_typeregister_function_get_type ())
#define VALA_TYPEREGISTER_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunction))
#define VALA_TYPEREGISTER_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunctionClass))
#define VALA_IS_TYPEREGISTER_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_TYPEREGISTER_FUNCTION))
#define VALA_IS_TYPEREGISTER_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_TYPEREGISTER_FUNCTION))
#define VALA_TYPEREGISTER_FUNCTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_TYPEREGISTER_FUNCTION, ValaTypeRegisterFunctionClass))

typedef struct _ValaTypeRegisterFunction ValaTypeRegisterFunction;
typedef struct _ValaTypeRegisterFunctionClass ValaTypeRegisterFunctionClass;

#define VALA_TYPE_STRUCT_REGISTER_FUNCTION (vala_struct_register_function_get_type ())
#define VALA_STRUCT_REGISTER_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_STRUCT_REGISTER_FUNCTION, ValaStructRegisterFunction))
#define VALA_STRUCT_REGISTER_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_STRUCT_REGISTER_FUNCTION, ValaStructRegisterFunctionClass))
#define VALA_IS_STRUCT_REGISTER_FUNCTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_STRUCT_REGISTER_FUNCTION))
#define VALA_IS_STRUCT_REGISTER_FUNCTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_STRUCT_REGISTER_FUNCTION))
#define VALA_STRUCT_REGISTER_FUNCTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_STRUCT_REGISTER_FUNCTION, ValaStructRegisterFunctionClass))

typedef struct _ValaStructRegisterFunction ValaStructRegisterFunction;
typedef struct _ValaStructRegisterFunctionClass ValaStructRegisterFunctionClass;
#define _vala_typeregister_function_unref0(var) ((var == NULL) ? NULL : (var = (vala_typeregister_function_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _vala_ccode_base_module_emit_context_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_base_module_emit_context_unref (var), NULL)))

#define VALA_TYPE_GLIB_VALUE (vala_glib_value_get_type ())
#define VALA_GLIB_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_GLIB_VALUE, ValaGLibValue))
#define VALA_GLIB_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_GLIB_VALUE, ValaGLibValueClass))
#define VALA_IS_GLIB_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_GLIB_VALUE))
#define VALA_IS_GLIB_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_GLIB_VALUE))
#define VALA_GLIB_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_GLIB_VALUE, ValaGLibValueClass))

typedef struct _ValaGLibValue ValaGLibValue;
typedef struct _ValaGLibValueClass ValaGLibValueClass;
#define _vala_target_value_unref0(var) ((var == NULL) ? NULL : (var = (vala_target_value_unref (var), NULL)))
typedef struct _ValaCCodeBaseModuleEmitContextPrivate ValaCCodeBaseModuleEmitContextPrivate;

struct _ValaCCodeBaseModule {
	ValaCodeGenerator parent_instance;
	ValaCCodeBaseModulePrivate * priv;
	ValaSymbol* root_symbol;
	ValaCCodeBaseModuleEmitContext* emit_context;
	ValaCCodeLineDirective* current_line;
	ValaCCodeFile* header_file;
	ValaCCodeFile* internal_header_file;
	ValaCCodeFile* cfile;
	ValaCCodeBaseModuleEmitContext* class_init_context;
	ValaCCodeBaseModuleEmitContext* base_init_context;
	ValaCCodeBaseModuleEmitContext* class_finalize_context;
	ValaCCodeBaseModuleEmitContext* base_finalize_context;
	ValaCCodeBaseModuleEmitContext* instance_init_context;
	ValaCCodeBaseModuleEmitContext* instance_finalize_context;
	ValaCCodeStruct* param_spec_struct;
	ValaCCodeStruct* closure_struct;
	ValaCCodeEnum* prop_enum;
	ValaSet* user_marshal_set;
	ValaSet* predefined_marshal_set;
	gint next_regex_id;
	gint next_coroutine_state;
	ValaDataType* void_type;
	ValaDataType* bool_type;
	ValaDataType* char_type;
	ValaDataType* uchar_type;
	ValaDataType* unichar_type;
	ValaDataType* short_type;
	ValaDataType* ushort_type;
	ValaDataType* int_type;
	ValaDataType* uint_type;
	ValaDataType* long_type;
	ValaDataType* ulong_type;
	ValaDataType* int8_type;
	ValaDataType* uint8_type;
	ValaDataType* int16_type;
	ValaDataType* uint16_type;
	ValaDataType* int32_type;
	ValaDataType* uint32_type;
	ValaDataType* int64_type;
	ValaDataType* uint64_type;
	ValaDataType* string_type;
	ValaDataType* regex_type;
	ValaDataType* float_type;
	ValaDataType* double_type;
	ValaTypeSymbol* gtype_type;
	ValaTypeSymbol* gobject_type;
	ValaErrorType* gerror_type;
	ValaClass* glist_type;
	ValaClass* gslist_type;
	ValaClass* gnode_type;
	ValaClass* gqueue_type;
	ValaClass* gvaluearray_type;
	ValaTypeSymbol* gstringbuilder_type;
	ValaTypeSymbol* garray_type;
	ValaTypeSymbol* gbytearray_type;
	ValaTypeSymbol* gptrarray_type;
	ValaTypeSymbol* gthreadpool_type;
	ValaDataType* gdestroynotify_type;
	ValaDataType* gquark_type;
	ValaStruct* gvalue_type;
	ValaClass* gvariant_type;
	ValaStruct* mutex_type;
	ValaTypeSymbol* type_module_type;
	ValaTypeSymbol* dbus_proxy_type;
	gboolean in_plugin;
	gchar* module_init_param_name;
	gboolean gvaluecollector_h_needed;
	gboolean requires_array_free;
	gboolean requires_array_move;
	gboolean requires_array_length;
	ValaSet* wrappers;
};

struct _ValaCCodeBaseModuleClass {
	ValaCodeGeneratorClass parent_class;
	void (*append_vala_array_free) (ValaCCodeBaseModule* self);
	void (*append_vala_array_move) (ValaCCodeBaseModule* self);
	void (*append_vala_array_length) (ValaCCodeBaseModule* self);
	gboolean (*generate_enum_declaration) (ValaCCodeBaseModule* self, ValaEnum* en, ValaCCodeFile* decl_space);
	void (*generate_class_struct_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_struct_declaration) (ValaCCodeBaseModule* self, ValaStruct* st, ValaCCodeFile* decl_space);
	void (*generate_delegate_declaration) (ValaCCodeBaseModule* self, ValaDelegate* d, ValaCCodeFile* decl_space);
	void (*generate_cparameters) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaMap* cparam_map, ValaCCodeFunction* func, ValaCCodeFunctionDeclarator* vdeclarator, ValaMap* carg_map, ValaCCodeFunctionCall* vcall, gint direction);
	ValaCCodeExpression* (*get_dup_func_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaSourceReference* source_reference, gboolean is_chainup);
	gchar* (*append_struct_array_free) (ValaCCodeBaseModule* self, ValaStruct* st);
	ValaCCodeExpression* (*destroy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, gboolean is_macro_definition);
	void (*append_scope_free) (ValaCCodeBaseModule* self, ValaSymbol* sym, ValaCodeNode* stop_at);
	ValaTargetValue* (*get_local_cvalue) (ValaCCodeBaseModule* self, ValaLocalVariable* local);
	ValaTargetValue* (*get_parameter_cvalue) (ValaCCodeBaseModule* self, ValaParameter* param);
	ValaTargetValue* (*get_field_cvalue) (ValaCCodeBaseModule* self, ValaField* field, ValaTargetValue* instance);
	ValaTargetValue* (*load_variable) (ValaCCodeBaseModule* self, ValaVariable* variable, ValaTargetValue* value);
	ValaTargetValue* (*load_this_parameter) (ValaCCodeBaseModule* self, ValaTypeSymbol* sym);
	void (*store_value) (ValaCCodeBaseModule* self, ValaTargetValue* lvalue, ValaTargetValue* value);
	gchar* (*get_delegate_target_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaCCodeExpression* (*get_delegate_target_cexpression) (ValaCCodeBaseModule* self, ValaExpression* delegate_expr, ValaCCodeExpression** delegate_target_destroy_notify);
	ValaCCodeExpression* (*get_delegate_target_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	ValaCCodeExpression* (*get_delegate_target_destroy_notify_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value);
	gchar* (*get_delegate_target_destroy_notify_cname) (ValaCCodeBaseModule* self, const gchar* delegate_cname);
	ValaTargetValue* (*copy_value) (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaCodeNode* node);
	void (*generate_class_declaration) (ValaCCodeBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_interface_declaration) (ValaCCodeBaseModule* self, ValaInterface* iface, ValaCCodeFile* decl_space);
	void (*generate_method_declaration) (ValaCCodeBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space);
	void (*generate_error_domain_declaration) (ValaCCodeBaseModule* self, ValaErrorDomain* edomain, ValaCCodeFile* decl_space);
	ValaCCodeExpression* (*deserialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* variant_expr, ValaCCodeExpression* expr, ValaCCodeExpression* error_expr, gboolean* may_fail);
	ValaCCodeExpression* (*serialize_expression) (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeExpression* expr);
	ValaCCodeExpression* (*get_implicit_cast_expression) (ValaCCodeBaseModule* self, ValaCCodeExpression* source_cexpr, ValaDataType* expression_type, ValaDataType* target_type, ValaCodeNode* node);
	void (*create_type_check_statement) (ValaCCodeBaseModule* self, ValaCodeNode* method_node, ValaDataType* ret_type, ValaTypeSymbol* t, gboolean non_null, const gchar* var_name);
	gboolean (*is_gobject_property) (ValaCCodeBaseModule* self, ValaProperty* prop);
	void (*generate_dynamic_method_wrapper) (ValaCCodeBaseModule* self, ValaDynamicMethod* method);
	gboolean (*method_has_wrapper) (ValaCCodeBaseModule* self, ValaMethod* method);
	ValaCCodeFunctionCall* (*get_param_spec) (ValaCCodeBaseModule* self, ValaProperty* prop);
	ValaCCodeFunctionCall* (*get_signal_creation) (ValaCCodeBaseModule* self, ValaSignal* sig, ValaTypeSymbol* type);
	void (*register_dbus_info) (ValaCCodeBaseModule* self, ValaCCodeBlock* block, ValaObjectTypeSymbol* bindable);
	gchar* (*get_dynamic_property_getter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_property_setter_cname) (ValaCCodeBaseModule* self, ValaDynamicProperty* node);
	gchar* (*get_dynamic_signal_cname) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_connect_after_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_dynamic_signal_disconnect_wrapper_name) (ValaCCodeBaseModule* self, ValaDynamicSignal* node);
	gchar* (*get_array_length_cname) (ValaCCodeBaseModule* self, const gchar* array_cname, gint dim);
	gchar* (*get_parameter_array_length_cname) (ValaCCodeBaseModule* self, ValaParameter* param, gint dim);
	ValaCCodeExpression* (*get_array_length_cexpression) (ValaCCodeBaseModule* self, ValaExpression* array_expr, gint dim);
	ValaCCodeExpression* (*get_array_length_cvalue) (ValaCCodeBaseModule* self, ValaTargetValue* value, gint dim);
	gchar* (*get_array_size_cname) (ValaCCodeBaseModule* self, const gchar* array_cname);
	void (*add_simple_check) (ValaCCodeBaseModule* self, ValaCodeNode* node, gboolean always_fails);
	gchar* (*generate_ready_function) (ValaCCodeBaseModule* self, ValaMethod* m);
};

struct _ValaCCodeStructModule {
	ValaCCodeBaseModule parent_instance;
	ValaCCodeStructModulePrivate * priv;
};

struct _ValaCCodeStructModuleClass {
	ValaCCodeBaseModuleClass parent_class;
};

struct _ValaCCodeBaseModuleEmitContext {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValaCCodeBaseModuleEmitContextPrivate * priv;
	ValaSymbol* current_symbol;
	ValaArrayList* symbol_stack;
	ValaTryStatement* current_try;
	ValaCatchClause* current_catch;
	ValaCCodeFunction* ccode;
	ValaArrayList* ccode_stack;
	ValaArrayList* temp_ref_values;
	gint next_temp_var_id;
	gboolean current_method_inner_error;
	gboolean current_method_return;
	ValaMap* variable_name_map;
	ValaMap* closure_variable_count_map;
	ValaMap* closure_variable_clash_map;
};

struct _ValaCCodeBaseModuleEmitContextClass {
	GTypeClass parent_class;
	void (*finalize) (ValaCCodeBaseModuleEmitContext *self);
};


static gpointer vala_ccode_struct_module_parent_class = NULL;

GType vala_ccode_base_module_get_type (void) G_GNUC_CONST;
gpointer vala_ccode_base_module_emit_context_ref (gpointer instance);
void vala_ccode_base_module_emit_context_unref (gpointer instance);
GParamSpec* vala_ccode_base_module_param_spec_emit_context (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_ccode_base_module_value_set_emit_context (GValue* value, gpointer v_object);
void vala_ccode_base_module_value_take_emit_context (GValue* value, gpointer v_object);
gpointer vala_ccode_base_module_value_get_emit_context (const GValue* value);
GType vala_ccode_base_module_emit_context_get_type (void) G_GNUC_CONST;
GType vala_ccode_struct_module_get_type (void) G_GNUC_CONST;
enum  {
	VALA_CCODE_STRUCT_MODULE_DUMMY_PROPERTY
};
static void vala_ccode_struct_module_real_generate_struct_declaration (ValaCCodeBaseModule* base, ValaStruct* st, ValaCCodeFile* decl_space);
gboolean vala_ccode_base_module_add_symbol_declaration (ValaCCodeBaseModule* self, ValaCCodeFile* decl_space, ValaSymbol* sym, const gchar* name);
gchar* vala_ccode_base_module_get_ccode_name (ValaCodeNode* node);
ValaCodeContext* vala_ccode_base_module_get_context (ValaCCodeBaseModule* self);
gboolean vala_ccode_base_module_get_ccode_has_type_id (ValaTypeSymbol* sym);
gchar* vala_ccode_base_module_get_ccode_lower_case_name (ValaCodeNode* node, const gchar* infix);
gchar* vala_ccode_base_module_get_ccode_type_id (ValaCodeNode* node);
ValaStructRegisterFunction* vala_struct_register_function_new (ValaStruct* st, ValaCodeContext* context);
ValaStructRegisterFunction* vala_struct_register_function_construct (GType object_type, ValaStruct* st, ValaCodeContext* context);
gpointer vala_typeregister_function_ref (gpointer instance);
void vala_typeregister_function_unref (gpointer instance);
GParamSpec* vala_param_spec_typeregister_function (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_value_set_typeregister_function (GValue* value, gpointer v_object);
void vala_value_take_typeregister_function (GValue* value, gpointer v_object);
gpointer vala_value_get_typeregister_function (const GValue* value);
GType vala_typeregister_function_get_type (void) G_GNUC_CONST;
GType vala_struct_register_function_get_type (void) G_GNUC_CONST;
void vala_typeregister_function_init_from_type (ValaTypeRegisterFunction* self, gboolean plugin, gboolean declaration_only);
ValaCCodeFragment* vala_typeregister_function_get_declaration (ValaTypeRegisterFunction* self);
void vala_ccode_base_module_generate_type_declaration (ValaCCodeBaseModule* self, ValaDataType* type, ValaCCodeFile* decl_space);
gchar* vala_ccode_base_module_get_ccode_declarator_suffix (ValaDataType* type);
gboolean vala_ccode_base_module_get_ccode_array_length (ValaCodeNode* node);
gchar* vala_ccode_base_module_get_ccode_array_length_name (ValaCodeNode* node);
gchar* vala_ccode_base_module_get_array_length_cname (ValaCCodeBaseModule* self, const gchar* array_cname, gint dim);
gchar* vala_ccode_base_module_get_array_size_cname (ValaCCodeBaseModule* self, const gchar* array_cname);
gchar* vala_ccode_base_module_get_ccode_delegate_target_name (ValaVariable* variable);
gchar* vala_ccode_base_module_get_delegate_target_destroy_notify_cname (ValaCCodeBaseModule* self, const gchar* delegate_cname);
gchar* vala_ccode_base_module_get_ccode_dup_function (ValaTypeSymbol* sym);
gchar* vala_ccode_base_module_get_ccode_free_function (ValaTypeSymbol* sym);
gchar* vala_ccode_base_module_get_ccode_copy_function (ValaTypeSymbol* sym);
gchar* vala_ccode_base_module_get_ccode_destroy_function (ValaTypeSymbol* sym);
static void vala_ccode_struct_module_real_visit_struct (ValaCodeVisitor* base, ValaStruct* st);
void vala_ccode_base_module_push_context (ValaCCodeBaseModule* self, ValaCCodeBaseModuleEmitContext* emit_context);
ValaCCodeBaseModuleEmitContext* vala_ccode_base_module_emit_context_new (ValaSymbol* symbol);
ValaCCodeBaseModuleEmitContext* vala_ccode_base_module_emit_context_construct (GType object_type, ValaSymbol* symbol);
void vala_ccode_base_module_push_line (ValaCCodeBaseModule* self, ValaSourceReference* source_reference);
void vala_ccode_base_module_generate_struct_declaration (ValaCCodeBaseModule* self, ValaStruct* st, ValaCCodeFile* decl_space);
static void vala_ccode_struct_module_begin_struct_destroy_function (ValaCCodeStructModule* self, ValaStruct* st);
static void vala_ccode_struct_module_add_struct_copy_function (ValaCCodeStructModule* self, ValaStruct* st);
static void vala_ccode_struct_module_add_struct_destroy_function (ValaCCodeStructModule* self, ValaStruct* st);
static void vala_ccode_struct_module_add_struct_dup_function (ValaCCodeStructModule* self, ValaStruct* st);
static void vala_ccode_struct_module_add_struct_free_function (ValaCCodeStructModule* self, ValaStruct* st);
void vala_ccode_base_module_pop_line (ValaCCodeBaseModule* self);
void vala_ccode_base_module_pop_context (ValaCCodeBaseModule* self);
void vala_ccode_base_module_push_function (ValaCCodeBaseModule* self, ValaCCodeFunction* func);
ValaCCodeFunction* vala_ccode_base_module_get_ccode (ValaCCodeBaseModule* self);
void vala_ccode_base_module_pop_function (ValaCCodeBaseModule* self);
ValaDataType* vala_ccode_base_module_get_data_type_for_symbol (ValaTypeSymbol* sym);
ValaGLibValue* vala_glib_value_new (ValaDataType* value_type, ValaCCodeExpression* cvalue, gboolean lvalue);
ValaGLibValue* vala_glib_value_construct (GType object_type, ValaDataType* value_type, ValaCCodeExpression* cvalue, gboolean lvalue);
GType vala_glib_value_get_type (void) G_GNUC_CONST;
ValaTargetValue* vala_ccode_base_module_load_this_parameter (ValaCCodeBaseModule* self, ValaTypeSymbol* sym);
gboolean vala_ccode_base_module_requires_copy (ValaCCodeBaseModule* self, ValaDataType* type);
ValaTargetValue* vala_ccode_base_module_copy_value (ValaCCodeBaseModule* self, ValaTargetValue* value, ValaCodeNode* node);
ValaCCodeStructModule* vala_ccode_struct_module_construct (GType object_type);
ValaCCodeBaseModule* vala_ccode_base_module_construct (GType object_type);


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


static void vala_ccode_struct_module_real_generate_struct_declaration (ValaCCodeBaseModule* base, ValaStruct* st, ValaCCodeFile* decl_space) {
	ValaCCodeStructModule * self;
	ValaCCodeFile* _tmp0_;
	ValaStruct* _tmp1_;
	ValaStruct* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_;
	ValaStruct* _tmp7_;
	gboolean _tmp8_ = FALSE;
	ValaCodeContext* _tmp13_;
	ValaCodeContext* _tmp14_;
	ValaProfile _tmp15_;
	ValaProfile _tmp16_;
	ValaStruct* _tmp43_;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_;
	gchar* _tmp46_ = NULL;
	gchar* _tmp47_;
	ValaCCodeStruct* _tmp48_;
	ValaCCodeStruct* _tmp49_;
	ValaCCodeStruct* instance_struct;
	ValaCCodeStruct* _tmp50_;
	ValaStruct* _tmp51_;
	gboolean _tmp52_;
	gboolean _tmp53_;
	ValaStruct* _tmp178_;
	ValaStruct* _tmp179_;
	ValaStruct* _tmp180_;
	ValaStruct* _tmp209_;
	gchar* _tmp210_ = NULL;
	gchar* _tmp211_;
	ValaStruct* _tmp212_;
	gchar* _tmp213_ = NULL;
	gchar* _tmp214_;
	gchar* _tmp215_;
	gchar* _tmp216_;
	ValaCCodeFunction* _tmp217_;
	ValaCCodeFunction* _tmp218_;
	ValaCCodeFunction* function;
	ValaStruct* _tmp219_;
	gboolean _tmp220_ = FALSE;
	ValaCCodeFunction* _tmp222_;
	ValaStruct* _tmp223_;
	gchar* _tmp224_ = NULL;
	gchar* _tmp225_;
	gchar* _tmp226_;
	gchar* _tmp227_;
	gchar* _tmp228_;
	gchar* _tmp229_;
	ValaCCodeParameter* _tmp230_;
	ValaCCodeParameter* _tmp231_;
	ValaCCodeFile* _tmp232_;
	ValaCCodeFunction* _tmp233_;
	ValaStruct* _tmp234_;
	gchar* _tmp235_ = NULL;
	gchar* _tmp236_;
	ValaCCodeFunction* _tmp237_;
	ValaStruct* _tmp238_;
	gboolean _tmp239_ = FALSE;
	ValaCCodeFunction* _tmp241_;
	ValaStruct* _tmp242_;
	gchar* _tmp243_ = NULL;
	gchar* _tmp244_;
	gchar* _tmp245_;
	gchar* _tmp246_;
	ValaCCodeParameter* _tmp247_;
	ValaCCodeParameter* _tmp248_;
	ValaCCodeFile* _tmp249_;
	ValaCCodeFunction* _tmp250_;
	ValaStruct* _tmp251_;
	gboolean _tmp252_ = FALSE;
	self = (ValaCCodeStructModule*) base;
	g_return_if_fail (st != NULL);
	g_return_if_fail (decl_space != NULL);
	_tmp0_ = decl_space;
	_tmp1_ = st;
	_tmp2_ = st;
	_tmp3_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = vala_ccode_base_module_add_symbol_declaration ((ValaCCodeBaseModule*) self, _tmp0_, (ValaSymbol*) _tmp1_, _tmp4_);
	_tmp6_ = _tmp5_;
	_g_free0 (_tmp4_);
	if (_tmp6_) {
		return;
	}
	_tmp7_ = st;
	_tmp8_ = vala_struct_is_boolean_type (_tmp7_);
	if (_tmp8_) {
		ValaCCodeFile* _tmp9_;
		_tmp9_ = decl_space;
		vala_ccode_file_add_include (_tmp9_, "stdbool.h", FALSE);
		return;
	} else {
		ValaStruct* _tmp10_;
		gboolean _tmp11_ = FALSE;
		_tmp10_ = st;
		_tmp11_ = vala_struct_is_integer_type (_tmp10_);
		if (_tmp11_) {
			ValaCCodeFile* _tmp12_;
			_tmp12_ = decl_space;
			vala_ccode_file_add_include (_tmp12_, "stdint.h", FALSE);
			return;
		}
	}
	_tmp13_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp14_ = _tmp13_;
	_tmp15_ = vala_code_context_get_profile (_tmp14_);
	_tmp16_ = _tmp15_;
	if (_tmp16_ == VALA_PROFILE_GOBJECT) {
		ValaStruct* _tmp17_;
		gboolean _tmp18_ = FALSE;
		_tmp17_ = st;
		_tmp18_ = vala_ccode_base_module_get_ccode_has_type_id ((ValaTypeSymbol*) _tmp17_);
		if (_tmp18_) {
			ValaCCodeFile* _tmp19_;
			ValaCCodeNewline* _tmp20_;
			ValaCCodeNewline* _tmp21_;
			ValaStruct* _tmp22_;
			gchar* _tmp23_ = NULL;
			gchar* _tmp24_;
			gchar* _tmp25_ = NULL;
			gchar* _tmp26_;
			gchar* macro;
			ValaCCodeFile* _tmp27_;
			ValaStruct* _tmp28_;
			gchar* _tmp29_ = NULL;
			gchar* _tmp30_;
			const gchar* _tmp31_;
			ValaCCodeMacroReplacement* _tmp32_;
			ValaCCodeMacroReplacement* _tmp33_;
			ValaStruct* _tmp34_;
			ValaCodeContext* _tmp35_;
			ValaCodeContext* _tmp36_;
			ValaStructRegisterFunction* _tmp37_;
			ValaStructRegisterFunction* type_fun;
			ValaStructRegisterFunction* _tmp38_;
			ValaCCodeFile* _tmp39_;
			ValaStructRegisterFunction* _tmp40_;
			ValaCCodeFragment* _tmp41_ = NULL;
			ValaCCodeFragment* _tmp42_;
			_tmp19_ = decl_space;
			_tmp20_ = vala_ccode_newline_new ();
			_tmp21_ = _tmp20_;
			vala_ccode_file_add_type_declaration (_tmp19_, (ValaCCodeNode*) _tmp21_);
			_vala_ccode_node_unref0 (_tmp21_);
			_tmp22_ = st;
			_tmp23_ = vala_ccode_base_module_get_ccode_lower_case_name ((ValaCodeNode*) _tmp22_, NULL);
			_tmp24_ = _tmp23_;
			_tmp25_ = g_strdup_printf ("(%s_get_type ())", _tmp24_);
			_tmp26_ = _tmp25_;
			_g_free0 (_tmp24_);
			macro = _tmp26_;
			_tmp27_ = decl_space;
			_tmp28_ = st;
			_tmp29_ = vala_ccode_base_module_get_ccode_type_id ((ValaCodeNode*) _tmp28_);
			_tmp30_ = _tmp29_;
			_tmp31_ = macro;
			_tmp32_ = vala_ccode_macro_replacement_new (_tmp30_, _tmp31_);
			_tmp33_ = _tmp32_;
			vala_ccode_file_add_type_declaration (_tmp27_, (ValaCCodeNode*) _tmp33_);
			_vala_ccode_node_unref0 (_tmp33_);
			_g_free0 (_tmp30_);
			_tmp34_ = st;
			_tmp35_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
			_tmp36_ = _tmp35_;
			_tmp37_ = vala_struct_register_function_new (_tmp34_, _tmp36_);
			type_fun = _tmp37_;
			_tmp38_ = type_fun;
			vala_typeregister_function_init_from_type ((ValaTypeRegisterFunction*) _tmp38_, FALSE, TRUE);
			_tmp39_ = decl_space;
			_tmp40_ = type_fun;
			_tmp41_ = vala_typeregister_function_get_declaration ((ValaTypeRegisterFunction*) _tmp40_);
			_tmp42_ = _tmp41_;
			vala_ccode_file_add_type_member_declaration (_tmp39_, (ValaCCodeNode*) _tmp42_);
			_vala_ccode_node_unref0 (_tmp42_);
			_vala_typeregister_function_unref0 (type_fun);
			_g_free0 (macro);
		}
	}
	_tmp43_ = st;
	_tmp44_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp43_);
	_tmp45_ = _tmp44_;
	_tmp46_ = g_strdup_printf ("_%s", _tmp45_);
	_tmp47_ = _tmp46_;
	_tmp48_ = vala_ccode_struct_new (_tmp47_);
	_tmp49_ = _tmp48_;
	_g_free0 (_tmp47_);
	_g_free0 (_tmp45_);
	instance_struct = _tmp49_;
	_tmp50_ = instance_struct;
	_tmp51_ = st;
	_tmp52_ = vala_symbol_get_deprecated ((ValaSymbol*) _tmp51_);
	_tmp53_ = _tmp52_;
	vala_ccode_struct_set_deprecated (_tmp50_, _tmp53_);
	{
		ValaStruct* _tmp54_;
		ValaList* _tmp55_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp56_;
		gint _tmp57_;
		gint _tmp58_;
		gint _f_size;
		gint _f_index;
		_tmp54_ = st;
		_tmp55_ = vala_struct_get_fields (_tmp54_);
		_f_list = _tmp55_;
		_tmp56_ = _f_list;
		_tmp57_ = vala_collection_get_size ((ValaCollection*) _tmp56_);
		_tmp58_ = _tmp57_;
		_f_size = _tmp58_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp59_;
			gint _tmp60_;
			gint _tmp61_;
			ValaList* _tmp62_;
			gint _tmp63_;
			gpointer _tmp64_ = NULL;
			ValaField* f;
			ValaField* _tmp65_;
			ValaDataType* _tmp66_;
			ValaDataType* _tmp67_;
			gchar* _tmp68_ = NULL;
			gchar* field_ctype;
			ValaField* _tmp69_;
			gboolean _tmp70_;
			gboolean _tmp71_;
			ValaField* _tmp74_;
			ValaMemberBinding _tmp75_;
			ValaMemberBinding _tmp76_;
			_tmp59_ = _f_index;
			_f_index = _tmp59_ + 1;
			_tmp60_ = _f_index;
			_tmp61_ = _f_size;
			if (!(_tmp60_ < _tmp61_)) {
				break;
			}
			_tmp62_ = _f_list;
			_tmp63_ = _f_index;
			_tmp64_ = vala_list_get (_tmp62_, _tmp63_);
			f = (ValaField*) _tmp64_;
			_tmp65_ = f;
			_tmp66_ = vala_variable_get_variable_type ((ValaVariable*) _tmp65_);
			_tmp67_ = _tmp66_;
			_tmp68_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp67_);
			field_ctype = _tmp68_;
			_tmp69_ = f;
			_tmp70_ = vala_field_get_is_volatile (_tmp69_);
			_tmp71_ = _tmp70_;
			if (_tmp71_) {
				const gchar* _tmp72_;
				gchar* _tmp73_;
				_tmp72_ = field_ctype;
				_tmp73_ = g_strconcat ("volatile ", _tmp72_, NULL);
				_g_free0 (field_ctype);
				field_ctype = _tmp73_;
			}
			_tmp74_ = f;
			_tmp75_ = vala_field_get_binding (_tmp74_);
			_tmp76_ = _tmp75_;
			if (_tmp76_ == VALA_MEMBER_BINDING_INSTANCE) {
				ValaField* _tmp77_;
				ValaDataType* _tmp78_;
				ValaDataType* _tmp79_;
				ValaCCodeFile* _tmp80_;
				const gchar* _tmp81_ = NULL;
				ValaField* _tmp82_;
				gboolean _tmp83_;
				gboolean _tmp84_;
				ValaCCodeStruct* _tmp85_;
				const gchar* _tmp86_;
				ValaField* _tmp87_;
				gchar* _tmp88_ = NULL;
				gchar* _tmp89_;
				ValaField* _tmp90_;
				ValaDataType* _tmp91_;
				ValaDataType* _tmp92_;
				gchar* _tmp93_ = NULL;
				gchar* _tmp94_;
				gchar* _tmp95_;
				gchar* _tmp96_;
				const gchar* _tmp97_;
				gboolean _tmp98_ = FALSE;
				ValaField* _tmp99_;
				ValaDataType* _tmp100_;
				ValaDataType* _tmp101_;
				gboolean _tmp104_;
				_tmp77_ = f;
				_tmp78_ = vala_variable_get_variable_type ((ValaVariable*) _tmp77_);
				_tmp79_ = _tmp78_;
				_tmp80_ = decl_space;
				vala_ccode_base_module_generate_type_declaration ((ValaCCodeBaseModule*) self, _tmp79_, _tmp80_);
				_tmp82_ = f;
				_tmp83_ = vala_symbol_get_deprecated ((ValaSymbol*) _tmp82_);
				_tmp84_ = _tmp83_;
				if (_tmp84_) {
					_tmp81_ = " G_GNUC_DEPRECATED";
				} else {
					_tmp81_ = NULL;
				}
				_tmp85_ = instance_struct;
				_tmp86_ = field_ctype;
				_tmp87_ = f;
				_tmp88_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp87_);
				_tmp89_ = _tmp88_;
				_tmp90_ = f;
				_tmp91_ = vala_variable_get_variable_type ((ValaVariable*) _tmp90_);
				_tmp92_ = _tmp91_;
				_tmp93_ = vala_ccode_base_module_get_ccode_declarator_suffix (_tmp92_);
				_tmp94_ = _tmp93_;
				_tmp95_ = g_strconcat (_tmp89_, _tmp94_, NULL);
				_tmp96_ = _tmp95_;
				_tmp97_ = _tmp81_;
				vala_ccode_struct_add_field (_tmp85_, _tmp86_, _tmp96_, _tmp97_);
				_g_free0 (_tmp96_);
				_g_free0 (_tmp94_);
				_g_free0 (_tmp89_);
				_tmp99_ = f;
				_tmp100_ = vala_variable_get_variable_type ((ValaVariable*) _tmp99_);
				_tmp101_ = _tmp100_;
				if (VALA_IS_ARRAY_TYPE (_tmp101_)) {
					ValaField* _tmp102_;
					gboolean _tmp103_ = FALSE;
					_tmp102_ = f;
					_tmp103_ = vala_ccode_base_module_get_ccode_array_length ((ValaCodeNode*) _tmp102_);
					_tmp98_ = _tmp103_;
				} else {
					_tmp98_ = FALSE;
				}
				_tmp104_ = _tmp98_;
				if (_tmp104_) {
					ValaField* _tmp105_;
					ValaDataType* _tmp106_;
					ValaDataType* _tmp107_;
					ValaArrayType* _tmp108_;
					ValaArrayType* array_type;
					ValaArrayType* _tmp109_;
					gboolean _tmp110_;
					gboolean _tmp111_;
					_tmp105_ = f;
					_tmp106_ = vala_variable_get_variable_type ((ValaVariable*) _tmp105_);
					_tmp107_ = _tmp106_;
					_tmp108_ = _vala_code_node_ref0 (VALA_ARRAY_TYPE (_tmp107_));
					array_type = _tmp108_;
					_tmp109_ = array_type;
					_tmp110_ = vala_array_type_get_fixed_length (_tmp109_);
					_tmp111_ = _tmp110_;
					if (!_tmp111_) {
						ValaDataType* _tmp112_;
						ValaDataType* _tmp113_ = NULL;
						ValaDataType* len_type;
						gboolean _tmp137_ = FALSE;
						ValaArrayType* _tmp138_;
						gint _tmp139_;
						gint _tmp140_;
						gboolean _tmp143_;
						_tmp112_ = ((ValaCCodeBaseModule*) self)->int_type;
						_tmp113_ = vala_data_type_copy (_tmp112_);
						len_type = _tmp113_;
						{
							gint dim;
							dim = 1;
							{
								gboolean _tmp114_;
								_tmp114_ = TRUE;
								while (TRUE) {
									gboolean _tmp115_;
									gint _tmp117_;
									ValaArrayType* _tmp118_;
									gint _tmp119_;
									gint _tmp120_;
									gchar* length_cname = NULL;
									ValaField* _tmp121_;
									gchar* _tmp122_ = NULL;
									gchar* _tmp123_;
									gboolean _tmp124_;
									ValaCCodeStruct* _tmp132_;
									ValaDataType* _tmp133_;
									gchar* _tmp134_ = NULL;
									gchar* _tmp135_;
									const gchar* _tmp136_;
									_tmp115_ = _tmp114_;
									if (!_tmp115_) {
										gint _tmp116_;
										_tmp116_ = dim;
										dim = _tmp116_ + 1;
									}
									_tmp114_ = FALSE;
									_tmp117_ = dim;
									_tmp118_ = array_type;
									_tmp119_ = vala_array_type_get_rank (_tmp118_);
									_tmp120_ = _tmp119_;
									if (!(_tmp117_ <= _tmp120_)) {
										break;
									}
									_tmp121_ = f;
									_tmp122_ = vala_ccode_base_module_get_ccode_array_length_name ((ValaCodeNode*) _tmp121_);
									_tmp123_ = _tmp122_;
									_tmp124_ = _tmp123_ != NULL;
									_g_free0 (_tmp123_);
									if (_tmp124_) {
										ValaField* _tmp125_;
										gchar* _tmp126_ = NULL;
										_tmp125_ = f;
										_tmp126_ = vala_ccode_base_module_get_ccode_array_length_name ((ValaCodeNode*) _tmp125_);
										_g_free0 (length_cname);
										length_cname = _tmp126_;
									} else {
										ValaField* _tmp127_;
										const gchar* _tmp128_;
										const gchar* _tmp129_;
										gint _tmp130_;
										gchar* _tmp131_ = NULL;
										_tmp127_ = f;
										_tmp128_ = vala_symbol_get_name ((ValaSymbol*) _tmp127_);
										_tmp129_ = _tmp128_;
										_tmp130_ = dim;
										_tmp131_ = vala_ccode_base_module_get_array_length_cname ((ValaCCodeBaseModule*) self, _tmp129_, _tmp130_);
										_g_free0 (length_cname);
										length_cname = _tmp131_;
									}
									_tmp132_ = instance_struct;
									_tmp133_ = len_type;
									_tmp134_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp133_);
									_tmp135_ = _tmp134_;
									_tmp136_ = length_cname;
									vala_ccode_struct_add_field (_tmp132_, _tmp135_, _tmp136_, NULL);
									_g_free0 (_tmp135_);
									_g_free0 (length_cname);
								}
							}
						}
						_tmp138_ = array_type;
						_tmp139_ = vala_array_type_get_rank (_tmp138_);
						_tmp140_ = _tmp139_;
						if (_tmp140_ == 1) {
							ValaField* _tmp141_;
							gboolean _tmp142_ = FALSE;
							_tmp141_ = f;
							_tmp142_ = vala_symbol_is_internal_symbol ((ValaSymbol*) _tmp141_);
							_tmp137_ = _tmp142_;
						} else {
							_tmp137_ = FALSE;
						}
						_tmp143_ = _tmp137_;
						if (_tmp143_) {
							ValaCCodeStruct* _tmp144_;
							ValaDataType* _tmp145_;
							gchar* _tmp146_ = NULL;
							gchar* _tmp147_;
							ValaField* _tmp148_;
							const gchar* _tmp149_;
							const gchar* _tmp150_;
							gchar* _tmp151_ = NULL;
							gchar* _tmp152_;
							_tmp144_ = instance_struct;
							_tmp145_ = len_type;
							_tmp146_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp145_);
							_tmp147_ = _tmp146_;
							_tmp148_ = f;
							_tmp149_ = vala_symbol_get_name ((ValaSymbol*) _tmp148_);
							_tmp150_ = _tmp149_;
							_tmp151_ = vala_ccode_base_module_get_array_size_cname ((ValaCCodeBaseModule*) self, _tmp150_);
							_tmp152_ = _tmp151_;
							vala_ccode_struct_add_field (_tmp144_, _tmp147_, _tmp152_, NULL);
							_g_free0 (_tmp152_);
							_g_free0 (_tmp147_);
						}
						_vala_code_node_unref0 (len_type);
					}
					_vala_code_node_unref0 (array_type);
				} else {
					ValaField* _tmp153_;
					ValaDataType* _tmp154_;
					ValaDataType* _tmp155_;
					_tmp153_ = f;
					_tmp154_ = vala_variable_get_variable_type ((ValaVariable*) _tmp153_);
					_tmp155_ = _tmp154_;
					if (VALA_IS_DELEGATE_TYPE (_tmp155_)) {
						ValaField* _tmp156_;
						ValaDataType* _tmp157_;
						ValaDataType* _tmp158_;
						ValaDelegateType* _tmp159_;
						ValaDelegateType* delegate_type;
						ValaDelegateType* _tmp160_;
						ValaDelegate* _tmp161_;
						ValaDelegate* _tmp162_;
						gboolean _tmp163_;
						gboolean _tmp164_;
						_tmp156_ = f;
						_tmp157_ = vala_variable_get_variable_type ((ValaVariable*) _tmp156_);
						_tmp158_ = _tmp157_;
						_tmp159_ = _vala_code_node_ref0 (VALA_DELEGATE_TYPE (_tmp158_));
						delegate_type = _tmp159_;
						_tmp160_ = delegate_type;
						_tmp161_ = vala_delegate_type_get_delegate_symbol (_tmp160_);
						_tmp162_ = _tmp161_;
						_tmp163_ = vala_delegate_get_has_target (_tmp162_);
						_tmp164_ = _tmp163_;
						if (_tmp164_) {
							ValaCCodeStruct* _tmp165_;
							ValaField* _tmp166_;
							gchar* _tmp167_ = NULL;
							gchar* _tmp168_;
							ValaDelegateType* _tmp169_;
							gboolean _tmp170_;
							gboolean _tmp171_;
							_tmp165_ = instance_struct;
							_tmp166_ = f;
							_tmp167_ = vala_ccode_base_module_get_ccode_delegate_target_name ((ValaVariable*) _tmp166_);
							_tmp168_ = _tmp167_;
							vala_ccode_struct_add_field (_tmp165_, "gpointer", _tmp168_, NULL);
							_g_free0 (_tmp168_);
							_tmp169_ = delegate_type;
							_tmp170_ = vala_data_type_get_value_owned ((ValaDataType*) _tmp169_);
							_tmp171_ = _tmp170_;
							if (_tmp171_) {
								ValaCCodeStruct* _tmp172_;
								ValaField* _tmp173_;
								const gchar* _tmp174_;
								const gchar* _tmp175_;
								gchar* _tmp176_ = NULL;
								gchar* _tmp177_;
								_tmp172_ = instance_struct;
								_tmp173_ = f;
								_tmp174_ = vala_symbol_get_name ((ValaSymbol*) _tmp173_);
								_tmp175_ = _tmp174_;
								_tmp176_ = vala_ccode_base_module_get_delegate_target_destroy_notify_cname ((ValaCCodeBaseModule*) self, _tmp175_);
								_tmp177_ = _tmp176_;
								vala_ccode_struct_add_field (_tmp172_, "GDestroyNotify", _tmp177_, NULL);
								_g_free0 (_tmp177_);
							}
						}
						_vala_code_node_unref0 (delegate_type);
					}
				}
			}
			_g_free0 (field_ctype);
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	_tmp178_ = st;
	_tmp179_ = vala_struct_get_base_struct (_tmp178_);
	_tmp180_ = _tmp179_;
	if (_tmp180_ == NULL) {
		ValaCCodeFile* _tmp181_;
		ValaStruct* _tmp182_;
		gchar* _tmp183_ = NULL;
		gchar* _tmp184_;
		gchar* _tmp185_ = NULL;
		gchar* _tmp186_;
		ValaStruct* _tmp187_;
		gchar* _tmp188_ = NULL;
		gchar* _tmp189_;
		ValaCCodeVariableDeclarator* _tmp190_;
		ValaCCodeVariableDeclarator* _tmp191_;
		ValaCCodeTypeDefinition* _tmp192_;
		ValaCCodeTypeDefinition* _tmp193_;
		ValaCCodeFile* _tmp194_;
		ValaCCodeStruct* _tmp195_;
		_tmp181_ = decl_space;
		_tmp182_ = st;
		_tmp183_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp182_);
		_tmp184_ = _tmp183_;
		_tmp185_ = g_strdup_printf ("struct _%s", _tmp184_);
		_tmp186_ = _tmp185_;
		_tmp187_ = st;
		_tmp188_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp187_);
		_tmp189_ = _tmp188_;
		_tmp190_ = vala_ccode_variable_declarator_new (_tmp189_, NULL, NULL);
		_tmp191_ = _tmp190_;
		_tmp192_ = vala_ccode_type_definition_new (_tmp186_, (ValaCCodeDeclarator*) _tmp191_);
		_tmp193_ = _tmp192_;
		vala_ccode_file_add_type_declaration (_tmp181_, (ValaCCodeNode*) _tmp193_);
		_vala_ccode_node_unref0 (_tmp193_);
		_vala_ccode_node_unref0 (_tmp191_);
		_g_free0 (_tmp189_);
		_g_free0 (_tmp186_);
		_g_free0 (_tmp184_);
		_tmp194_ = decl_space;
		_tmp195_ = instance_struct;
		vala_ccode_file_add_type_definition (_tmp194_, (ValaCCodeNode*) _tmp195_);
	} else {
		ValaCCodeFile* _tmp196_;
		ValaStruct* _tmp197_;
		ValaStruct* _tmp198_;
		ValaStruct* _tmp199_;
		gchar* _tmp200_ = NULL;
		gchar* _tmp201_;
		ValaStruct* _tmp202_;
		gchar* _tmp203_ = NULL;
		gchar* _tmp204_;
		ValaCCodeVariableDeclarator* _tmp205_;
		ValaCCodeVariableDeclarator* _tmp206_;
		ValaCCodeTypeDefinition* _tmp207_;
		ValaCCodeTypeDefinition* _tmp208_;
		_tmp196_ = decl_space;
		_tmp197_ = st;
		_tmp198_ = vala_struct_get_base_struct (_tmp197_);
		_tmp199_ = _tmp198_;
		_tmp200_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp199_);
		_tmp201_ = _tmp200_;
		_tmp202_ = st;
		_tmp203_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp202_);
		_tmp204_ = _tmp203_;
		_tmp205_ = vala_ccode_variable_declarator_new (_tmp204_, NULL, NULL);
		_tmp206_ = _tmp205_;
		_tmp207_ = vala_ccode_type_definition_new (_tmp201_, (ValaCCodeDeclarator*) _tmp206_);
		_tmp208_ = _tmp207_;
		vala_ccode_file_add_type_declaration (_tmp196_, (ValaCCodeNode*) _tmp208_);
		_vala_ccode_node_unref0 (_tmp208_);
		_vala_ccode_node_unref0 (_tmp206_);
		_g_free0 (_tmp204_);
		_g_free0 (_tmp201_);
	}
	_tmp209_ = st;
	_tmp210_ = vala_ccode_base_module_get_ccode_dup_function ((ValaTypeSymbol*) _tmp209_);
	_tmp211_ = _tmp210_;
	_tmp212_ = st;
	_tmp213_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp212_);
	_tmp214_ = _tmp213_;
	_tmp215_ = g_strconcat (_tmp214_, "*", NULL);
	_tmp216_ = _tmp215_;
	_tmp217_ = vala_ccode_function_new (_tmp211_, _tmp216_);
	_tmp218_ = _tmp217_;
	_g_free0 (_tmp216_);
	_g_free0 (_tmp214_);
	_g_free0 (_tmp211_);
	function = _tmp218_;
	_tmp219_ = st;
	_tmp220_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp219_);
	if (_tmp220_) {
		ValaCCodeFunction* _tmp221_;
		_tmp221_ = function;
		vala_ccode_function_set_modifiers (_tmp221_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp222_ = function;
	_tmp223_ = st;
	_tmp224_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp223_);
	_tmp225_ = _tmp224_;
	_tmp226_ = g_strconcat ("const ", _tmp225_, NULL);
	_tmp227_ = _tmp226_;
	_tmp228_ = g_strconcat (_tmp227_, "*", NULL);
	_tmp229_ = _tmp228_;
	_tmp230_ = vala_ccode_parameter_new ("self", _tmp229_);
	_tmp231_ = _tmp230_;
	vala_ccode_function_add_parameter (_tmp222_, _tmp231_);
	_vala_ccode_node_unref0 (_tmp231_);
	_g_free0 (_tmp229_);
	_g_free0 (_tmp227_);
	_g_free0 (_tmp225_);
	_tmp232_ = decl_space;
	_tmp233_ = function;
	vala_ccode_file_add_function_declaration (_tmp232_, _tmp233_);
	_tmp234_ = st;
	_tmp235_ = vala_ccode_base_module_get_ccode_free_function ((ValaTypeSymbol*) _tmp234_);
	_tmp236_ = _tmp235_;
	_tmp237_ = vala_ccode_function_new (_tmp236_, "void");
	_vala_ccode_node_unref0 (function);
	function = _tmp237_;
	_g_free0 (_tmp236_);
	_tmp238_ = st;
	_tmp239_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp238_);
	if (_tmp239_) {
		ValaCCodeFunction* _tmp240_;
		_tmp240_ = function;
		vala_ccode_function_set_modifiers (_tmp240_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp241_ = function;
	_tmp242_ = st;
	_tmp243_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp242_);
	_tmp244_ = _tmp243_;
	_tmp245_ = g_strconcat (_tmp244_, "*", NULL);
	_tmp246_ = _tmp245_;
	_tmp247_ = vala_ccode_parameter_new ("self", _tmp246_);
	_tmp248_ = _tmp247_;
	vala_ccode_function_add_parameter (_tmp241_, _tmp248_);
	_vala_ccode_node_unref0 (_tmp248_);
	_g_free0 (_tmp246_);
	_g_free0 (_tmp244_);
	_tmp249_ = decl_space;
	_tmp250_ = function;
	vala_ccode_file_add_function_declaration (_tmp249_, _tmp250_);
	_tmp251_ = st;
	_tmp252_ = vala_struct_is_disposable (_tmp251_);
	if (_tmp252_) {
		ValaStruct* _tmp253_;
		gchar* _tmp254_ = NULL;
		gchar* _tmp255_;
		ValaCCodeFunction* _tmp256_;
		ValaStruct* _tmp257_;
		gboolean _tmp258_ = FALSE;
		ValaCCodeFunction* _tmp260_;
		ValaStruct* _tmp261_;
		gchar* _tmp262_ = NULL;
		gchar* _tmp263_;
		gchar* _tmp264_;
		gchar* _tmp265_;
		gchar* _tmp266_;
		gchar* _tmp267_;
		ValaCCodeParameter* _tmp268_;
		ValaCCodeParameter* _tmp269_;
		ValaCCodeFunction* _tmp270_;
		ValaStruct* _tmp271_;
		gchar* _tmp272_ = NULL;
		gchar* _tmp273_;
		gchar* _tmp274_;
		gchar* _tmp275_;
		ValaCCodeParameter* _tmp276_;
		ValaCCodeParameter* _tmp277_;
		ValaCCodeFile* _tmp278_;
		ValaCCodeFunction* _tmp279_;
		ValaStruct* _tmp280_;
		gchar* _tmp281_ = NULL;
		gchar* _tmp282_;
		ValaCCodeFunction* _tmp283_;
		ValaStruct* _tmp284_;
		gboolean _tmp285_ = FALSE;
		ValaCCodeFunction* _tmp287_;
		ValaStruct* _tmp288_;
		gchar* _tmp289_ = NULL;
		gchar* _tmp290_;
		gchar* _tmp291_;
		gchar* _tmp292_;
		ValaCCodeParameter* _tmp293_;
		ValaCCodeParameter* _tmp294_;
		ValaCCodeFile* _tmp295_;
		ValaCCodeFunction* _tmp296_;
		_tmp253_ = st;
		_tmp254_ = vala_ccode_base_module_get_ccode_copy_function ((ValaTypeSymbol*) _tmp253_);
		_tmp255_ = _tmp254_;
		_tmp256_ = vala_ccode_function_new (_tmp255_, "void");
		_vala_ccode_node_unref0 (function);
		function = _tmp256_;
		_g_free0 (_tmp255_);
		_tmp257_ = st;
		_tmp258_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp257_);
		if (_tmp258_) {
			ValaCCodeFunction* _tmp259_;
			_tmp259_ = function;
			vala_ccode_function_set_modifiers (_tmp259_, VALA_CCODE_MODIFIERS_STATIC);
		}
		_tmp260_ = function;
		_tmp261_ = st;
		_tmp262_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp261_);
		_tmp263_ = _tmp262_;
		_tmp264_ = g_strconcat ("const ", _tmp263_, NULL);
		_tmp265_ = _tmp264_;
		_tmp266_ = g_strconcat (_tmp265_, "*", NULL);
		_tmp267_ = _tmp266_;
		_tmp268_ = vala_ccode_parameter_new ("self", _tmp267_);
		_tmp269_ = _tmp268_;
		vala_ccode_function_add_parameter (_tmp260_, _tmp269_);
		_vala_ccode_node_unref0 (_tmp269_);
		_g_free0 (_tmp267_);
		_g_free0 (_tmp265_);
		_g_free0 (_tmp263_);
		_tmp270_ = function;
		_tmp271_ = st;
		_tmp272_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp271_);
		_tmp273_ = _tmp272_;
		_tmp274_ = g_strconcat (_tmp273_, "*", NULL);
		_tmp275_ = _tmp274_;
		_tmp276_ = vala_ccode_parameter_new ("dest", _tmp275_);
		_tmp277_ = _tmp276_;
		vala_ccode_function_add_parameter (_tmp270_, _tmp277_);
		_vala_ccode_node_unref0 (_tmp277_);
		_g_free0 (_tmp275_);
		_g_free0 (_tmp273_);
		_tmp278_ = decl_space;
		_tmp279_ = function;
		vala_ccode_file_add_function_declaration (_tmp278_, _tmp279_);
		_tmp280_ = st;
		_tmp281_ = vala_ccode_base_module_get_ccode_destroy_function ((ValaTypeSymbol*) _tmp280_);
		_tmp282_ = _tmp281_;
		_tmp283_ = vala_ccode_function_new (_tmp282_, "void");
		_vala_ccode_node_unref0 (function);
		function = _tmp283_;
		_g_free0 (_tmp282_);
		_tmp284_ = st;
		_tmp285_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp284_);
		if (_tmp285_) {
			ValaCCodeFunction* _tmp286_;
			_tmp286_ = function;
			vala_ccode_function_set_modifiers (_tmp286_, VALA_CCODE_MODIFIERS_STATIC);
		}
		_tmp287_ = function;
		_tmp288_ = st;
		_tmp289_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp288_);
		_tmp290_ = _tmp289_;
		_tmp291_ = g_strconcat (_tmp290_, "*", NULL);
		_tmp292_ = _tmp291_;
		_tmp293_ = vala_ccode_parameter_new ("self", _tmp292_);
		_tmp294_ = _tmp293_;
		vala_ccode_function_add_parameter (_tmp287_, _tmp294_);
		_vala_ccode_node_unref0 (_tmp294_);
		_g_free0 (_tmp292_);
		_g_free0 (_tmp290_);
		_tmp295_ = decl_space;
		_tmp296_ = function;
		vala_ccode_file_add_function_declaration (_tmp295_, _tmp296_);
	}
	_vala_ccode_node_unref0 (function);
	_vala_ccode_node_unref0 (instance_struct);
}


static gpointer _vala_ccode_base_module_emit_context_ref0 (gpointer self) {
	return self ? vala_ccode_base_module_emit_context_ref (self) : NULL;
}


static void vala_ccode_struct_module_real_visit_struct (ValaCodeVisitor* base, ValaStruct* st) {
	ValaCCodeStructModule * self;
	ValaStruct* _tmp0_;
	ValaCCodeBaseModuleEmitContext* _tmp1_;
	ValaCCodeBaseModuleEmitContext* _tmp2_;
	ValaStruct* _tmp3_;
	ValaSourceReference* _tmp4_;
	ValaSourceReference* _tmp5_;
	ValaCCodeBaseModuleEmitContext* _tmp6_;
	ValaCCodeBaseModuleEmitContext* _tmp7_;
	ValaCCodeBaseModuleEmitContext* old_instance_finalize_context;
	ValaCCodeBaseModuleEmitContext* _tmp8_;
	ValaStruct* _tmp9_;
	ValaCCodeFile* _tmp10_;
	ValaStruct* _tmp11_;
	gboolean _tmp12_ = FALSE;
	ValaStruct* _tmp15_;
	gboolean _tmp16_ = FALSE;
	gboolean _tmp19_ = FALSE;
	gboolean _tmp20_ = FALSE;
	ValaStruct* _tmp21_;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp25_;
	gboolean _tmp28_;
	ValaStruct* _tmp32_;
	gboolean _tmp33_ = FALSE;
	gboolean _tmp34_ = FALSE;
	ValaStruct* _tmp35_;
	gboolean _tmp36_ = FALSE;
	gboolean _tmp39_;
	gboolean _tmp42_;
	ValaCCodeBaseModuleEmitContext* _tmp49_;
	ValaCCodeBaseModuleEmitContext* _tmp50_;
	self = (ValaCCodeStructModule*) base;
	g_return_if_fail (st != NULL);
	_tmp0_ = st;
	_tmp1_ = vala_ccode_base_module_emit_context_new ((ValaSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	vala_ccode_base_module_push_context ((ValaCCodeBaseModule*) self, _tmp2_);
	_vala_ccode_base_module_emit_context_unref0 (_tmp2_);
	_tmp3_ = st;
	_tmp4_ = vala_code_node_get_source_reference ((ValaCodeNode*) _tmp3_);
	_tmp5_ = _tmp4_;
	vala_ccode_base_module_push_line ((ValaCCodeBaseModule*) self, _tmp5_);
	_tmp6_ = ((ValaCCodeBaseModule*) self)->instance_finalize_context;
	_tmp7_ = _vala_ccode_base_module_emit_context_ref0 (_tmp6_);
	old_instance_finalize_context = _tmp7_;
	_tmp8_ = vala_ccode_base_module_emit_context_new (NULL);
	_vala_ccode_base_module_emit_context_unref0 (((ValaCCodeBaseModule*) self)->instance_finalize_context);
	((ValaCCodeBaseModule*) self)->instance_finalize_context = _tmp8_;
	_tmp9_ = st;
	_tmp10_ = ((ValaCCodeBaseModule*) self)->cfile;
	vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, _tmp9_, _tmp10_);
	_tmp11_ = st;
	_tmp12_ = vala_symbol_is_internal_symbol ((ValaSymbol*) _tmp11_);
	if (!_tmp12_) {
		ValaStruct* _tmp13_;
		ValaCCodeFile* _tmp14_;
		_tmp13_ = st;
		_tmp14_ = ((ValaCCodeBaseModule*) self)->header_file;
		vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, _tmp13_, _tmp14_);
	}
	_tmp15_ = st;
	_tmp16_ = vala_symbol_is_private_symbol ((ValaSymbol*) _tmp15_);
	if (!_tmp16_) {
		ValaStruct* _tmp17_;
		ValaCCodeFile* _tmp18_;
		_tmp17_ = st;
		_tmp18_ = ((ValaCCodeBaseModule*) self)->internal_header_file;
		vala_ccode_base_module_generate_struct_declaration ((ValaCCodeBaseModule*) self, _tmp17_, _tmp18_);
	}
	_tmp21_ = st;
	_tmp22_ = vala_struct_is_boolean_type (_tmp21_);
	if (!_tmp22_) {
		ValaStruct* _tmp23_;
		gboolean _tmp24_ = FALSE;
		_tmp23_ = st;
		_tmp24_ = vala_struct_is_integer_type (_tmp23_);
		_tmp20_ = !_tmp24_;
	} else {
		_tmp20_ = FALSE;
	}
	_tmp25_ = _tmp20_;
	if (_tmp25_) {
		ValaStruct* _tmp26_;
		gboolean _tmp27_ = FALSE;
		_tmp26_ = st;
		_tmp27_ = vala_struct_is_floating_type (_tmp26_);
		_tmp19_ = !_tmp27_;
	} else {
		_tmp19_ = FALSE;
	}
	_tmp28_ = _tmp19_;
	if (_tmp28_) {
		ValaStruct* _tmp29_;
		gboolean _tmp30_ = FALSE;
		_tmp29_ = st;
		_tmp30_ = vala_struct_is_disposable (_tmp29_);
		if (_tmp30_) {
			ValaStruct* _tmp31_;
			_tmp31_ = st;
			vala_ccode_struct_module_begin_struct_destroy_function (self, _tmp31_);
		}
	}
	_tmp32_ = st;
	vala_code_node_accept_children ((ValaCodeNode*) _tmp32_, (ValaCodeVisitor*) self);
	_tmp35_ = st;
	_tmp36_ = vala_struct_is_boolean_type (_tmp35_);
	if (!_tmp36_) {
		ValaStruct* _tmp37_;
		gboolean _tmp38_ = FALSE;
		_tmp37_ = st;
		_tmp38_ = vala_struct_is_integer_type (_tmp37_);
		_tmp34_ = !_tmp38_;
	} else {
		_tmp34_ = FALSE;
	}
	_tmp39_ = _tmp34_;
	if (_tmp39_) {
		ValaStruct* _tmp40_;
		gboolean _tmp41_ = FALSE;
		_tmp40_ = st;
		_tmp41_ = vala_struct_is_floating_type (_tmp40_);
		_tmp33_ = !_tmp41_;
	} else {
		_tmp33_ = FALSE;
	}
	_tmp42_ = _tmp33_;
	if (_tmp42_) {
		ValaStruct* _tmp43_;
		gboolean _tmp44_ = FALSE;
		ValaStruct* _tmp47_;
		ValaStruct* _tmp48_;
		_tmp43_ = st;
		_tmp44_ = vala_struct_is_disposable (_tmp43_);
		if (_tmp44_) {
			ValaStruct* _tmp45_;
			ValaStruct* _tmp46_;
			_tmp45_ = st;
			vala_ccode_struct_module_add_struct_copy_function (self, _tmp45_);
			_tmp46_ = st;
			vala_ccode_struct_module_add_struct_destroy_function (self, _tmp46_);
		}
		_tmp47_ = st;
		vala_ccode_struct_module_add_struct_dup_function (self, _tmp47_);
		_tmp48_ = st;
		vala_ccode_struct_module_add_struct_free_function (self, _tmp48_);
	}
	_tmp49_ = old_instance_finalize_context;
	_tmp50_ = _vala_ccode_base_module_emit_context_ref0 (_tmp49_);
	_vala_ccode_base_module_emit_context_unref0 (((ValaCCodeBaseModule*) self)->instance_finalize_context);
	((ValaCCodeBaseModule*) self)->instance_finalize_context = _tmp50_;
	vala_ccode_base_module_pop_line ((ValaCCodeBaseModule*) self);
	vala_ccode_base_module_pop_context ((ValaCCodeBaseModule*) self);
	_vala_ccode_base_module_emit_context_unref0 (old_instance_finalize_context);
}


static void vala_ccode_struct_module_add_struct_dup_function (ValaCCodeStructModule* self, ValaStruct* st) {
	ValaStruct* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	ValaStruct* _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	ValaCCodeFunction* _tmp8_;
	ValaCCodeFunction* _tmp9_;
	ValaCCodeFunction* function;
	ValaStruct* _tmp10_;
	ValaSymbolAccessibility _tmp11_;
	ValaSymbolAccessibility _tmp12_;
	ValaCCodeFunction* _tmp14_;
	ValaStruct* _tmp15_;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	ValaCCodeParameter* _tmp22_;
	ValaCCodeParameter* _tmp23_;
	ValaCCodeFunction* _tmp24_;
	ValaCCodeFunction* _tmp25_;
	ValaCCodeFunction* _tmp26_;
	ValaStruct* _tmp27_;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	ValaCCodeVariableDeclarator* _tmp32_;
	ValaCCodeVariableDeclarator* _tmp33_;
	ValaCodeContext* _tmp34_;
	ValaCodeContext* _tmp35_;
	ValaProfile _tmp36_;
	ValaProfile _tmp37_;
	ValaStruct* _tmp80_;
	gboolean _tmp81_ = FALSE;
	ValaCCodeFunction* _tmp124_;
	ValaCCodeFunction* _tmp125_;
	ValaCCodeIdentifier* _tmp126_;
	ValaCCodeIdentifier* _tmp127_;
	ValaCCodeFile* _tmp128_;
	ValaCCodeFunction* _tmp129_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = st;
	_tmp1_ = vala_ccode_base_module_get_ccode_dup_function ((ValaTypeSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = st;
	_tmp4_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, "*", NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = vala_ccode_function_new (_tmp2_, _tmp7_);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	function = _tmp9_;
	_tmp10_ = st;
	_tmp11_ = vala_symbol_get_access ((ValaSymbol*) _tmp10_);
	_tmp12_ = _tmp11_;
	if (_tmp12_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
		ValaCCodeFunction* _tmp13_;
		_tmp13_ = function;
		vala_ccode_function_set_modifiers (_tmp13_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp14_ = function;
	_tmp15_ = st;
	_tmp16_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat ("const ", _tmp17_, NULL);
	_tmp19_ = _tmp18_;
	_tmp20_ = g_strconcat (_tmp19_, "*", NULL);
	_tmp21_ = _tmp20_;
	_tmp22_ = vala_ccode_parameter_new ("self", _tmp21_);
	_tmp23_ = _tmp22_;
	vala_ccode_function_add_parameter (_tmp14_, _tmp23_);
	_vala_ccode_node_unref0 (_tmp23_);
	_g_free0 (_tmp21_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_tmp24_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp24_);
	_tmp25_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp26_ = _tmp25_;
	_tmp27_ = st;
	_tmp28_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp27_);
	_tmp29_ = _tmp28_;
	_tmp30_ = g_strconcat (_tmp29_, "*", NULL);
	_tmp31_ = _tmp30_;
	_tmp32_ = vala_ccode_variable_declarator_new ("dup", NULL, NULL);
	_tmp33_ = _tmp32_;
	vala_ccode_function_add_declaration (_tmp26_, _tmp31_, (ValaCCodeDeclarator*) _tmp33_, 0);
	_vala_ccode_node_unref0 (_tmp33_);
	_g_free0 (_tmp31_);
	_g_free0 (_tmp29_);
	_tmp34_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp35_ = _tmp34_;
	_tmp36_ = vala_code_context_get_profile (_tmp35_);
	_tmp37_ = _tmp36_;
	if (_tmp37_ == VALA_PROFILE_GOBJECT) {
		ValaCCodeIdentifier* _tmp38_;
		ValaCCodeIdentifier* _tmp39_;
		ValaCCodeFunctionCall* _tmp40_;
		ValaCCodeFunctionCall* _tmp41_;
		ValaCCodeFunctionCall* creation_call;
		ValaCCodeFunctionCall* _tmp42_;
		ValaStruct* _tmp43_;
		gchar* _tmp44_ = NULL;
		gchar* _tmp45_;
		ValaCCodeConstant* _tmp46_;
		ValaCCodeConstant* _tmp47_;
		ValaCCodeFunctionCall* _tmp48_;
		ValaCCodeConstant* _tmp49_;
		ValaCCodeConstant* _tmp50_;
		ValaCCodeFunction* _tmp51_;
		ValaCCodeFunction* _tmp52_;
		ValaCCodeIdentifier* _tmp53_;
		ValaCCodeIdentifier* _tmp54_;
		ValaCCodeFunctionCall* _tmp55_;
		_tmp38_ = vala_ccode_identifier_new ("g_new0");
		_tmp39_ = _tmp38_;
		_tmp40_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp39_);
		_tmp41_ = _tmp40_;
		_vala_ccode_node_unref0 (_tmp39_);
		creation_call = _tmp41_;
		_tmp42_ = creation_call;
		_tmp43_ = st;
		_tmp44_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp43_);
		_tmp45_ = _tmp44_;
		_tmp46_ = vala_ccode_constant_new (_tmp45_);
		_tmp47_ = _tmp46_;
		vala_ccode_function_call_add_argument (_tmp42_, (ValaCCodeExpression*) _tmp47_);
		_vala_ccode_node_unref0 (_tmp47_);
		_g_free0 (_tmp45_);
		_tmp48_ = creation_call;
		_tmp49_ = vala_ccode_constant_new ("1");
		_tmp50_ = _tmp49_;
		vala_ccode_function_call_add_argument (_tmp48_, (ValaCCodeExpression*) _tmp50_);
		_vala_ccode_node_unref0 (_tmp50_);
		_tmp51_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp52_ = _tmp51_;
		_tmp53_ = vala_ccode_identifier_new ("dup");
		_tmp54_ = _tmp53_;
		_tmp55_ = creation_call;
		vala_ccode_function_add_assignment (_tmp52_, (ValaCCodeExpression*) _tmp54_, (ValaCCodeExpression*) _tmp55_);
		_vala_ccode_node_unref0 (_tmp54_);
		_vala_ccode_node_unref0 (creation_call);
	} else {
		ValaCodeContext* _tmp56_;
		ValaCodeContext* _tmp57_;
		ValaProfile _tmp58_;
		ValaProfile _tmp59_;
		_tmp56_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp57_ = _tmp56_;
		_tmp58_ = vala_code_context_get_profile (_tmp57_);
		_tmp59_ = _tmp58_;
		if (_tmp59_ == VALA_PROFILE_POSIX) {
			ValaCCodeIdentifier* _tmp60_;
			ValaCCodeIdentifier* _tmp61_;
			ValaCCodeFunctionCall* _tmp62_;
			ValaCCodeFunctionCall* _tmp63_;
			ValaCCodeFunctionCall* creation_call;
			ValaCCodeFunctionCall* _tmp64_;
			ValaCCodeConstant* _tmp65_;
			ValaCCodeConstant* _tmp66_;
			ValaCCodeFunctionCall* _tmp67_;
			ValaStruct* _tmp68_;
			gchar* _tmp69_ = NULL;
			gchar* _tmp70_;
			gchar* _tmp71_ = NULL;
			gchar* _tmp72_;
			ValaCCodeIdentifier* _tmp73_;
			ValaCCodeIdentifier* _tmp74_;
			ValaCCodeFunction* _tmp75_;
			ValaCCodeFunction* _tmp76_;
			ValaCCodeIdentifier* _tmp77_;
			ValaCCodeIdentifier* _tmp78_;
			ValaCCodeFunctionCall* _tmp79_;
			_tmp60_ = vala_ccode_identifier_new ("calloc");
			_tmp61_ = _tmp60_;
			_tmp62_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp61_);
			_tmp63_ = _tmp62_;
			_vala_ccode_node_unref0 (_tmp61_);
			creation_call = _tmp63_;
			_tmp64_ = creation_call;
			_tmp65_ = vala_ccode_constant_new ("1");
			_tmp66_ = _tmp65_;
			vala_ccode_function_call_add_argument (_tmp64_, (ValaCCodeExpression*) _tmp66_);
			_vala_ccode_node_unref0 (_tmp66_);
			_tmp67_ = creation_call;
			_tmp68_ = st;
			_tmp69_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp68_);
			_tmp70_ = _tmp69_;
			_tmp71_ = g_strdup_printf ("sizeof (%s*)", _tmp70_);
			_tmp72_ = _tmp71_;
			_tmp73_ = vala_ccode_identifier_new (_tmp72_);
			_tmp74_ = _tmp73_;
			vala_ccode_function_call_add_argument (_tmp67_, (ValaCCodeExpression*) _tmp74_);
			_vala_ccode_node_unref0 (_tmp74_);
			_g_free0 (_tmp72_);
			_g_free0 (_tmp70_);
			_tmp75_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp76_ = _tmp75_;
			_tmp77_ = vala_ccode_identifier_new ("dup");
			_tmp78_ = _tmp77_;
			_tmp79_ = creation_call;
			vala_ccode_function_add_assignment (_tmp76_, (ValaCCodeExpression*) _tmp78_, (ValaCCodeExpression*) _tmp79_);
			_vala_ccode_node_unref0 (_tmp78_);
			_vala_ccode_node_unref0 (creation_call);
		}
	}
	_tmp80_ = st;
	_tmp81_ = vala_struct_is_disposable (_tmp80_);
	if (_tmp81_) {
		ValaStruct* _tmp82_;
		gchar* _tmp83_ = NULL;
		gchar* _tmp84_;
		ValaCCodeIdentifier* _tmp85_;
		ValaCCodeIdentifier* _tmp86_;
		ValaCCodeFunctionCall* _tmp87_;
		ValaCCodeFunctionCall* _tmp88_;
		ValaCCodeFunctionCall* copy_call;
		ValaCCodeFunctionCall* _tmp89_;
		ValaCCodeIdentifier* _tmp90_;
		ValaCCodeIdentifier* _tmp91_;
		ValaCCodeFunctionCall* _tmp92_;
		ValaCCodeIdentifier* _tmp93_;
		ValaCCodeIdentifier* _tmp94_;
		ValaCCodeFunction* _tmp95_;
		ValaCCodeFunction* _tmp96_;
		ValaCCodeFunctionCall* _tmp97_;
		_tmp82_ = st;
		_tmp83_ = vala_ccode_base_module_get_ccode_copy_function ((ValaTypeSymbol*) _tmp82_);
		_tmp84_ = _tmp83_;
		_tmp85_ = vala_ccode_identifier_new (_tmp84_);
		_tmp86_ = _tmp85_;
		_tmp87_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp86_);
		_tmp88_ = _tmp87_;
		_vala_ccode_node_unref0 (_tmp86_);
		_g_free0 (_tmp84_);
		copy_call = _tmp88_;
		_tmp89_ = copy_call;
		_tmp90_ = vala_ccode_identifier_new ("self");
		_tmp91_ = _tmp90_;
		vala_ccode_function_call_add_argument (_tmp89_, (ValaCCodeExpression*) _tmp91_);
		_vala_ccode_node_unref0 (_tmp91_);
		_tmp92_ = copy_call;
		_tmp93_ = vala_ccode_identifier_new ("dup");
		_tmp94_ = _tmp93_;
		vala_ccode_function_call_add_argument (_tmp92_, (ValaCCodeExpression*) _tmp94_);
		_vala_ccode_node_unref0 (_tmp94_);
		_tmp95_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp96_ = _tmp95_;
		_tmp97_ = copy_call;
		vala_ccode_function_add_expression (_tmp96_, (ValaCCodeExpression*) _tmp97_);
		_vala_ccode_node_unref0 (copy_call);
	} else {
		ValaCCodeFile* _tmp98_;
		ValaCCodeIdentifier* _tmp99_;
		ValaCCodeIdentifier* _tmp100_;
		ValaCCodeFunctionCall* _tmp101_;
		ValaCCodeFunctionCall* _tmp102_;
		ValaCCodeFunctionCall* sizeof_call;
		ValaCCodeFunctionCall* _tmp103_;
		ValaStruct* _tmp104_;
		gchar* _tmp105_ = NULL;
		gchar* _tmp106_;
		ValaCCodeConstant* _tmp107_;
		ValaCCodeConstant* _tmp108_;
		ValaCCodeIdentifier* _tmp109_;
		ValaCCodeIdentifier* _tmp110_;
		ValaCCodeFunctionCall* _tmp111_;
		ValaCCodeFunctionCall* _tmp112_;
		ValaCCodeFunctionCall* copy_call;
		ValaCCodeFunctionCall* _tmp113_;
		ValaCCodeIdentifier* _tmp114_;
		ValaCCodeIdentifier* _tmp115_;
		ValaCCodeFunctionCall* _tmp116_;
		ValaCCodeIdentifier* _tmp117_;
		ValaCCodeIdentifier* _tmp118_;
		ValaCCodeFunctionCall* _tmp119_;
		ValaCCodeFunctionCall* _tmp120_;
		ValaCCodeFunction* _tmp121_;
		ValaCCodeFunction* _tmp122_;
		ValaCCodeFunctionCall* _tmp123_;
		_tmp98_ = ((ValaCCodeBaseModule*) self)->cfile;
		vala_ccode_file_add_include (_tmp98_, "string.h", FALSE);
		_tmp99_ = vala_ccode_identifier_new ("sizeof");
		_tmp100_ = _tmp99_;
		_tmp101_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp100_);
		_tmp102_ = _tmp101_;
		_vala_ccode_node_unref0 (_tmp100_);
		sizeof_call = _tmp102_;
		_tmp103_ = sizeof_call;
		_tmp104_ = st;
		_tmp105_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp104_);
		_tmp106_ = _tmp105_;
		_tmp107_ = vala_ccode_constant_new (_tmp106_);
		_tmp108_ = _tmp107_;
		vala_ccode_function_call_add_argument (_tmp103_, (ValaCCodeExpression*) _tmp108_);
		_vala_ccode_node_unref0 (_tmp108_);
		_g_free0 (_tmp106_);
		_tmp109_ = vala_ccode_identifier_new ("memcpy");
		_tmp110_ = _tmp109_;
		_tmp111_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp110_);
		_tmp112_ = _tmp111_;
		_vala_ccode_node_unref0 (_tmp110_);
		copy_call = _tmp112_;
		_tmp113_ = copy_call;
		_tmp114_ = vala_ccode_identifier_new ("dup");
		_tmp115_ = _tmp114_;
		vala_ccode_function_call_add_argument (_tmp113_, (ValaCCodeExpression*) _tmp115_);
		_vala_ccode_node_unref0 (_tmp115_);
		_tmp116_ = copy_call;
		_tmp117_ = vala_ccode_identifier_new ("self");
		_tmp118_ = _tmp117_;
		vala_ccode_function_call_add_argument (_tmp116_, (ValaCCodeExpression*) _tmp118_);
		_vala_ccode_node_unref0 (_tmp118_);
		_tmp119_ = copy_call;
		_tmp120_ = sizeof_call;
		vala_ccode_function_call_add_argument (_tmp119_, (ValaCCodeExpression*) _tmp120_);
		_tmp121_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp122_ = _tmp121_;
		_tmp123_ = copy_call;
		vala_ccode_function_add_expression (_tmp122_, (ValaCCodeExpression*) _tmp123_);
		_vala_ccode_node_unref0 (copy_call);
		_vala_ccode_node_unref0 (sizeof_call);
	}
	_tmp124_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp125_ = _tmp124_;
	_tmp126_ = vala_ccode_identifier_new ("dup");
	_tmp127_ = _tmp126_;
	vala_ccode_function_add_return (_tmp125_, (ValaCCodeExpression*) _tmp127_);
	_vala_ccode_node_unref0 (_tmp127_);
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp128_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp129_ = function;
	vala_ccode_file_add_function (_tmp128_, _tmp129_);
	_vala_ccode_node_unref0 (function);
}


static void vala_ccode_struct_module_add_struct_free_function (ValaCCodeStructModule* self, ValaStruct* st) {
	ValaStruct* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	ValaCCodeFunction* _tmp4_;
	ValaCCodeFunction* function;
	ValaStruct* _tmp5_;
	ValaSymbolAccessibility _tmp6_;
	ValaSymbolAccessibility _tmp7_;
	ValaCCodeFunction* _tmp9_;
	ValaStruct* _tmp10_;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	ValaCCodeParameter* _tmp15_;
	ValaCCodeParameter* _tmp16_;
	ValaCCodeFunction* _tmp17_;
	ValaStruct* _tmp18_;
	gboolean _tmp19_ = FALSE;
	ValaCodeContext* _tmp33_;
	ValaCodeContext* _tmp34_;
	ValaProfile _tmp35_;
	ValaProfile _tmp36_;
	ValaCCodeFile* _tmp61_;
	ValaCCodeFunction* _tmp62_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = st;
	_tmp1_ = vala_ccode_base_module_get_ccode_free_function ((ValaTypeSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_ccode_function_new (_tmp2_, "void");
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	function = _tmp4_;
	_tmp5_ = st;
	_tmp6_ = vala_symbol_get_access ((ValaSymbol*) _tmp5_);
	_tmp7_ = _tmp6_;
	if (_tmp7_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
		ValaCCodeFunction* _tmp8_;
		_tmp8_ = function;
		vala_ccode_function_set_modifiers (_tmp8_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp9_ = function;
	_tmp10_ = st;
	_tmp11_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat (_tmp12_, "*", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = vala_ccode_parameter_new ("self", _tmp14_);
	_tmp16_ = _tmp15_;
	vala_ccode_function_add_parameter (_tmp9_, _tmp16_);
	_vala_ccode_node_unref0 (_tmp16_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_tmp17_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp17_);
	_tmp18_ = st;
	_tmp19_ = vala_struct_is_disposable (_tmp18_);
	if (_tmp19_) {
		ValaStruct* _tmp20_;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_;
		ValaCCodeIdentifier* _tmp23_;
		ValaCCodeIdentifier* _tmp24_;
		ValaCCodeFunctionCall* _tmp25_;
		ValaCCodeFunctionCall* _tmp26_;
		ValaCCodeFunctionCall* destroy_call;
		ValaCCodeFunctionCall* _tmp27_;
		ValaCCodeIdentifier* _tmp28_;
		ValaCCodeIdentifier* _tmp29_;
		ValaCCodeFunction* _tmp30_;
		ValaCCodeFunction* _tmp31_;
		ValaCCodeFunctionCall* _tmp32_;
		_tmp20_ = st;
		_tmp21_ = vala_ccode_base_module_get_ccode_destroy_function ((ValaTypeSymbol*) _tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = vala_ccode_identifier_new (_tmp22_);
		_tmp24_ = _tmp23_;
		_tmp25_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp24_);
		_tmp26_ = _tmp25_;
		_vala_ccode_node_unref0 (_tmp24_);
		_g_free0 (_tmp22_);
		destroy_call = _tmp26_;
		_tmp27_ = destroy_call;
		_tmp28_ = vala_ccode_identifier_new ("self");
		_tmp29_ = _tmp28_;
		vala_ccode_function_call_add_argument (_tmp27_, (ValaCCodeExpression*) _tmp29_);
		_vala_ccode_node_unref0 (_tmp29_);
		_tmp30_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp31_ = _tmp30_;
		_tmp32_ = destroy_call;
		vala_ccode_function_add_expression (_tmp31_, (ValaCCodeExpression*) _tmp32_);
		_vala_ccode_node_unref0 (destroy_call);
	}
	_tmp33_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp34_ = _tmp33_;
	_tmp35_ = vala_code_context_get_profile (_tmp34_);
	_tmp36_ = _tmp35_;
	if (_tmp36_ == VALA_PROFILE_GOBJECT) {
		ValaCCodeIdentifier* _tmp37_;
		ValaCCodeIdentifier* _tmp38_;
		ValaCCodeFunctionCall* _tmp39_;
		ValaCCodeFunctionCall* _tmp40_;
		ValaCCodeFunctionCall* free_call;
		ValaCCodeFunctionCall* _tmp41_;
		ValaCCodeIdentifier* _tmp42_;
		ValaCCodeIdentifier* _tmp43_;
		ValaCCodeFunction* _tmp44_;
		ValaCCodeFunction* _tmp45_;
		ValaCCodeFunctionCall* _tmp46_;
		_tmp37_ = vala_ccode_identifier_new ("g_free");
		_tmp38_ = _tmp37_;
		_tmp39_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp38_);
		_tmp40_ = _tmp39_;
		_vala_ccode_node_unref0 (_tmp38_);
		free_call = _tmp40_;
		_tmp41_ = free_call;
		_tmp42_ = vala_ccode_identifier_new ("self");
		_tmp43_ = _tmp42_;
		vala_ccode_function_call_add_argument (_tmp41_, (ValaCCodeExpression*) _tmp43_);
		_vala_ccode_node_unref0 (_tmp43_);
		_tmp44_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp45_ = _tmp44_;
		_tmp46_ = free_call;
		vala_ccode_function_add_expression (_tmp45_, (ValaCCodeExpression*) _tmp46_);
		_vala_ccode_node_unref0 (free_call);
	} else {
		ValaCodeContext* _tmp47_;
		ValaCodeContext* _tmp48_;
		ValaProfile _tmp49_;
		ValaProfile _tmp50_;
		_tmp47_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
		_tmp48_ = _tmp47_;
		_tmp49_ = vala_code_context_get_profile (_tmp48_);
		_tmp50_ = _tmp49_;
		if (_tmp50_ == VALA_PROFILE_POSIX) {
			ValaCCodeIdentifier* _tmp51_;
			ValaCCodeIdentifier* _tmp52_;
			ValaCCodeFunctionCall* _tmp53_;
			ValaCCodeFunctionCall* _tmp54_;
			ValaCCodeFunctionCall* free_call;
			ValaCCodeFunctionCall* _tmp55_;
			ValaCCodeIdentifier* _tmp56_;
			ValaCCodeIdentifier* _tmp57_;
			ValaCCodeFunction* _tmp58_;
			ValaCCodeFunction* _tmp59_;
			ValaCCodeFunctionCall* _tmp60_;
			_tmp51_ = vala_ccode_identifier_new ("free");
			_tmp52_ = _tmp51_;
			_tmp53_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp52_);
			_tmp54_ = _tmp53_;
			_vala_ccode_node_unref0 (_tmp52_);
			free_call = _tmp54_;
			_tmp55_ = free_call;
			_tmp56_ = vala_ccode_identifier_new ("self");
			_tmp57_ = _tmp56_;
			vala_ccode_function_call_add_argument (_tmp55_, (ValaCCodeExpression*) _tmp57_);
			_vala_ccode_node_unref0 (_tmp57_);
			_tmp58_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp59_ = _tmp58_;
			_tmp60_ = free_call;
			vala_ccode_function_add_expression (_tmp59_, (ValaCCodeExpression*) _tmp60_);
			_vala_ccode_node_unref0 (free_call);
		}
	}
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp61_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp62_ = function;
	vala_ccode_file_add_function (_tmp61_, _tmp62_);
	_vala_ccode_node_unref0 (function);
}


static void vala_ccode_struct_module_add_struct_copy_function (ValaCCodeStructModule* self, ValaStruct* st) {
	ValaStruct* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	ValaCCodeFunction* _tmp4_;
	ValaCCodeFunction* function;
	ValaStruct* _tmp5_;
	ValaSymbolAccessibility _tmp6_;
	ValaSymbolAccessibility _tmp7_;
	ValaCCodeFunction* _tmp9_;
	ValaStruct* _tmp10_;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	ValaCCodeParameter* _tmp17_;
	ValaCCodeParameter* _tmp18_;
	ValaCCodeFunction* _tmp19_;
	ValaStruct* _tmp20_;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	ValaCCodeParameter* _tmp25_;
	ValaCCodeParameter* _tmp26_;
	ValaCCodeFunction* _tmp27_;
	ValaStruct* _tmp28_;
	ValaDataType* _tmp29_ = NULL;
	ValaDataType* _tmp30_;
	ValaCCodeIdentifier* _tmp31_;
	ValaCCodeIdentifier* _tmp32_;
	ValaGLibValue* _tmp33_;
	ValaGLibValue* _tmp34_;
	ValaGLibValue* dest_struct;
	ValaCCodeFile* _tmp66_;
	ValaCCodeFunction* _tmp67_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = st;
	_tmp1_ = vala_ccode_base_module_get_ccode_copy_function ((ValaTypeSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_ccode_function_new (_tmp2_, "void");
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	function = _tmp4_;
	_tmp5_ = st;
	_tmp6_ = vala_symbol_get_access ((ValaSymbol*) _tmp5_);
	_tmp7_ = _tmp6_;
	if (_tmp7_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
		ValaCCodeFunction* _tmp8_;
		_tmp8_ = function;
		vala_ccode_function_set_modifiers (_tmp8_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp9_ = function;
	_tmp10_ = st;
	_tmp11_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat ("const ", _tmp12_, NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp14_, "*", NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = vala_ccode_parameter_new ("self", _tmp16_);
	_tmp18_ = _tmp17_;
	vala_ccode_function_add_parameter (_tmp9_, _tmp18_);
	_vala_ccode_node_unref0 (_tmp18_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_tmp19_ = function;
	_tmp20_ = st;
	_tmp21_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp20_);
	_tmp22_ = _tmp21_;
	_tmp23_ = g_strconcat (_tmp22_, "*", NULL);
	_tmp24_ = _tmp23_;
	_tmp25_ = vala_ccode_parameter_new ("dest", _tmp24_);
	_tmp26_ = _tmp25_;
	vala_ccode_function_add_parameter (_tmp19_, _tmp26_);
	_vala_ccode_node_unref0 (_tmp26_);
	_g_free0 (_tmp24_);
	_g_free0 (_tmp22_);
	_tmp27_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp27_);
	_tmp28_ = st;
	_tmp29_ = vala_ccode_base_module_get_data_type_for_symbol ((ValaTypeSymbol*) _tmp28_);
	_tmp30_ = _tmp29_;
	_tmp31_ = vala_ccode_identifier_new ("(*dest)");
	_tmp32_ = _tmp31_;
	_tmp33_ = vala_glib_value_new (_tmp30_, (ValaCCodeExpression*) _tmp32_, TRUE);
	_tmp34_ = _tmp33_;
	_vala_ccode_node_unref0 (_tmp32_);
	_vala_code_node_unref0 (_tmp30_);
	dest_struct = _tmp34_;
	{
		ValaStruct* _tmp35_;
		ValaList* _tmp36_ = NULL;
		ValaList* _f_list;
		ValaList* _tmp37_;
		gint _tmp38_;
		gint _tmp39_;
		gint _f_size;
		gint _f_index;
		_tmp35_ = st;
		_tmp36_ = vala_struct_get_fields (_tmp35_);
		_f_list = _tmp36_;
		_tmp37_ = _f_list;
		_tmp38_ = vala_collection_get_size ((ValaCollection*) _tmp37_);
		_tmp39_ = _tmp38_;
		_f_size = _tmp39_;
		_f_index = -1;
		while (TRUE) {
			gint _tmp40_;
			gint _tmp41_;
			gint _tmp42_;
			ValaList* _tmp43_;
			gint _tmp44_;
			gpointer _tmp45_ = NULL;
			ValaField* f;
			ValaField* _tmp46_;
			ValaMemberBinding _tmp47_;
			ValaMemberBinding _tmp48_;
			_tmp40_ = _f_index;
			_f_index = _tmp40_ + 1;
			_tmp41_ = _f_index;
			_tmp42_ = _f_size;
			if (!(_tmp41_ < _tmp42_)) {
				break;
			}
			_tmp43_ = _f_list;
			_tmp44_ = _f_index;
			_tmp45_ = vala_list_get (_tmp43_, _tmp44_);
			f = (ValaField*) _tmp45_;
			_tmp46_ = f;
			_tmp47_ = vala_field_get_binding (_tmp46_);
			_tmp48_ = _tmp47_;
			if (_tmp48_ == VALA_MEMBER_BINDING_INSTANCE) {
				ValaField* _tmp49_;
				ValaStruct* _tmp50_;
				ValaTargetValue* _tmp51_ = NULL;
				ValaTargetValue* _tmp52_;
				ValaTargetValue* _tmp53_ = NULL;
				ValaTargetValue* _tmp54_;
				ValaTargetValue* value;
				ValaField* _tmp55_;
				ValaDataType* _tmp56_;
				ValaDataType* _tmp57_;
				gboolean _tmp58_ = FALSE;
				ValaField* _tmp63_;
				ValaGLibValue* _tmp64_;
				ValaTargetValue* _tmp65_;
				_tmp49_ = f;
				_tmp50_ = st;
				_tmp51_ = vala_ccode_base_module_load_this_parameter ((ValaCCodeBaseModule*) self, VALA_TYPESYMBOL (_tmp50_));
				_tmp52_ = _tmp51_;
				_tmp53_ = vala_code_generator_load_field ((ValaCodeGenerator*) self, _tmp49_, _tmp52_);
				_tmp54_ = _tmp53_;
				_vala_target_value_unref0 (_tmp52_);
				value = _tmp54_;
				_tmp55_ = f;
				_tmp56_ = vala_variable_get_variable_type ((ValaVariable*) _tmp55_);
				_tmp57_ = _tmp56_;
				_tmp58_ = vala_ccode_base_module_requires_copy ((ValaCCodeBaseModule*) self, _tmp57_);
				if (_tmp58_) {
					ValaTargetValue* _tmp59_;
					ValaField* _tmp60_;
					ValaTargetValue* _tmp61_ = NULL;
					ValaTargetValue* _tmp62_;
					_tmp59_ = value;
					_tmp60_ = f;
					_tmp61_ = vala_ccode_base_module_copy_value ((ValaCCodeBaseModule*) self, _tmp59_, (ValaCodeNode*) _tmp60_);
					_vala_target_value_unref0 (value);
					value = _tmp61_;
					_tmp62_ = value;
					if (_tmp62_ == NULL) {
						_vala_target_value_unref0 (value);
						_vala_code_node_unref0 (f);
						continue;
					}
				}
				_tmp63_ = f;
				_tmp64_ = dest_struct;
				_tmp65_ = value;
				vala_code_generator_store_field ((ValaCodeGenerator*) self, _tmp63_, (ValaTargetValue*) _tmp64_, _tmp65_);
				_vala_target_value_unref0 (value);
			}
			_vala_code_node_unref0 (f);
		}
		_vala_iterable_unref0 (_f_list);
	}
	vala_ccode_base_module_pop_function ((ValaCCodeBaseModule*) self);
	_tmp66_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp67_ = function;
	vala_ccode_file_add_function (_tmp66_, _tmp67_);
	_vala_target_value_unref0 (dest_struct);
	_vala_ccode_node_unref0 (function);
}


static void vala_ccode_struct_module_begin_struct_destroy_function (ValaCCodeStructModule* self, ValaStruct* st) {
	ValaCCodeBaseModuleEmitContext* _tmp0_;
	ValaStruct* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	ValaCCodeFunction* _tmp4_;
	ValaCCodeFunction* _tmp5_;
	ValaCCodeFunction* function;
	ValaStruct* _tmp6_;
	ValaSymbolAccessibility _tmp7_;
	ValaSymbolAccessibility _tmp8_;
	ValaCCodeFunction* _tmp10_;
	ValaStruct* _tmp11_;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	ValaCCodeParameter* _tmp16_;
	ValaCCodeParameter* _tmp17_;
	ValaCCodeFunction* _tmp18_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = ((ValaCCodeBaseModule*) self)->instance_finalize_context;
	vala_ccode_base_module_push_context ((ValaCCodeBaseModule*) self, _tmp0_);
	_tmp1_ = st;
	_tmp2_ = vala_ccode_base_module_get_ccode_destroy_function ((ValaTypeSymbol*) _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_ccode_function_new (_tmp3_, "void");
	_tmp5_ = _tmp4_;
	_g_free0 (_tmp3_);
	function = _tmp5_;
	_tmp6_ = st;
	_tmp7_ = vala_symbol_get_access ((ValaSymbol*) _tmp6_);
	_tmp8_ = _tmp7_;
	if (_tmp8_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
		ValaCCodeFunction* _tmp9_;
		_tmp9_ = function;
		vala_ccode_function_set_modifiers (_tmp9_, VALA_CCODE_MODIFIERS_STATIC);
	}
	_tmp10_ = function;
	_tmp11_ = st;
	_tmp12_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, "*", NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = vala_ccode_parameter_new ("self", _tmp15_);
	_tmp17_ = _tmp16_;
	vala_ccode_function_add_parameter (_tmp10_, _tmp17_);
	_vala_ccode_node_unref0 (_tmp17_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_tmp18_ = function;
	vala_ccode_base_module_push_function ((ValaCCodeBaseModule*) self, _tmp18_);
	vala_ccode_base_module_pop_context ((ValaCCodeBaseModule*) self);
	_vala_ccode_node_unref0 (function);
}


static void vala_ccode_struct_module_add_struct_destroy_function (ValaCCodeStructModule* self, ValaStruct* st) {
	ValaCCodeFile* _tmp0_;
	ValaCCodeBaseModuleEmitContext* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (st != NULL);
	_tmp0_ = ((ValaCCodeBaseModule*) self)->cfile;
	_tmp1_ = ((ValaCCodeBaseModule*) self)->instance_finalize_context;
	_tmp2_ = _tmp1_->ccode;
	vala_ccode_file_add_function (_tmp0_, _tmp2_);
}


ValaCCodeStructModule* vala_ccode_struct_module_construct (GType object_type) {
	ValaCCodeStructModule* self = NULL;
	self = (ValaCCodeStructModule*) vala_ccode_base_module_construct (object_type);
	return self;
}


static void vala_ccode_struct_module_class_init (ValaCCodeStructModuleClass * klass) {
	vala_ccode_struct_module_parent_class = g_type_class_peek_parent (klass);
	VALA_CCODE_BASE_MODULE_CLASS (klass)->generate_struct_declaration = vala_ccode_struct_module_real_generate_struct_declaration;
	VALA_CODE_VISITOR_CLASS (klass)->visit_struct = vala_ccode_struct_module_real_visit_struct;
}


static void vala_ccode_struct_module_instance_init (ValaCCodeStructModule * self) {
}


GType vala_ccode_struct_module_get_type (void) {
	static volatile gsize vala_ccode_struct_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_ccode_struct_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaCCodeStructModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_ccode_struct_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaCCodeStructModule), 0, (GInstanceInitFunc) vala_ccode_struct_module_instance_init, NULL };
		GType vala_ccode_struct_module_type_id;
		vala_ccode_struct_module_type_id = g_type_register_static (VALA_TYPE_CCODE_BASE_MODULE, "ValaCCodeStructModule", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&vala_ccode_struct_module_type_id__volatile, vala_ccode_struct_module_type_id);
	}
	return vala_ccode_struct_module_type_id__volatile;
}



